# Generated by Django 5.1.7 on 2025-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('standard', models.CharField(choices=[('8', '8th'), ('9', '9th'), ('10', '10th'), ('12', '12th')], max_length=2)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('SSC', 'SSC'), ('HSC', 'HSC')], max_length=4)),
                ('school', models.CharField(max_length=50)),
                ('subjects', models.CharField(choices=[('ENG', 'English'), ('SS', 'Social Studies'), ('BOTH', 'Both')], max_length=4)),
                ('branch', models.CharField(choices=[('GULMOHAR', 'Gulmohar Road'), ('MARKET', 'Market Yard')], max_length=10)),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash')], max_length=10)),
                ('receipt', models.FileField(upload_to='receipts/')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
