# Generated by Django 5.2 on 2025-04-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0004_alter_studentregistration_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='father_name',
            field=models.CharField(default='father', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_occupation',
            field=models.CharField(default='occupation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_phone',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='student_img/'),
        ),
    ]
